[package]
name = "simple_logger"
version = "0.5.0"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "A logger that prints all messages with a readable output format"
repository = "https://github.com/borntyping/rust-simple_logger"

[dependencies]
log = { version = "^0.4.1", features = ["std"] }
chrono = "0.4.6"
