[package]
name = "simple_logger"
version = "1.2.0"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "A logger that prints all messages with a readable output format"
repository = "https://github.com/borntyping/rust-simple_logger"

[features]
default = ["colored"]

[dependencies]
log = { version = "^0.4.5", features = ["std"] }
chrono = "0.4.6"
colored = { version = "^1.6", optional = true }
